name: GitHub Actions Build
on:
  push:
    branches:
      - main
jobs:
  my_first_job:
    name: template
    runs-on: "self-hosted"
    steps:
      working-directory: /usr/template/package
      - uses: actions/checkout@v2
      - run: |
        ls > c.txt
